enginer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path("auth/", include("login.urls")), 
    path("plataforma/", include("plataforma.urls")),
    path("", lambda request: redirect('auth/login/'))


]

login/urls.py
from django.urls import path
from . import views
from django.shortcuts import redirect

urlpatterns = [
    path("login/", views.login, name='login'),
    path("cadastro/", views.cadastro, name='cadastro'),
    path("validar_login/", views.validar_login, name='validar_login'),
    path("validar_cadastro/", views.validar_cadastro, name='validar_cadastro'),
    path("recuperar/", views.recuperar_senha, name='recuperar_senha'),
    path("validar_token/", views.validar_token, name='validar_token'),
    path("recuperar_acesso/", views.recuperar_acesso, name='recuperar_acesso'),
    path("update/", views.update_view, name='update'),
    path("update_password/", views.update_password, name='update_password'),
    path("funcionario_novo/", views.update_view_funcionario, name='funcionario_novo'),
    path("update_funcionario/", views.update_funcionario, name='update_funcionario'),

]

plataforma/urls.py
from django.urls import path
from . import views
from django.shortcuts import redirect
urlpatterns = [
    path("", views.plataforma, name='plataforma'),
    path("novo/", views.renderizar_cadastro, name='cadastro_projeto'),
    path("sair/", views.sair, name="sair"),
    path("cadastrar_projeto/", views.cadastro_projeto, name='cadastro_projeto'),
    path("selecionar_empresa/", views.selecionar_empresa, name='selecionar_empresa'),
    path("home/", views.renderizar_plataforma, name='renderizar_plataforma'),
    path('iniciar_tarefa/', views.iniciar_tarefa, name='iniciar_tarefa'),
    path('enviar_banco_horas/', views.enviar_banco_horas, name='enviar_banco_horas'),
    path('atualizar_registro/', views.atualizar_registro_reprovada, name='atualizar_registro'),
    path('renderizar_cadastro/', views.renderizar_cadastro, name='renderizar_cadastro'),
    path('novo_projeto/', views.novo_projeto, name='novo_projeto'),
    path("cadastrar_tarefa/", views.cadastrar_tarefa, name="cadastrar_tarefa"),
    path("cadastrar_informacoes/", views.cadastrar_informacoes, name="cadastrar_informacoes"),
    path("criar_cliente/", views.criar_cliente, name="criar_cliente"),
    path("atualizar_registro_aprovada/", views.atualizar_registro_aprovada, name="atualizar_registro_aprovada"),
    path("analisar/", views.exibir_grafico, name="analisar"),
    path('editar_usuario/', views.editar_usuario, name='editar_usuario'),
    path('salvar_perfil/', views.salvar_perfil, name='salvar_perfil'),
    path('cadastrar_projeto', views.criar_projeto, name='cadastrar_projeto'),
    path('projetos/', views.listar_projeto, name='projetos'),
    path('equipe/', views.renderizar_equipe, name='equipe'),
    path('cadastrar_funcionario/', views.cadastrar_funcionario, name='cadastrar_funcionario'),
    path('get-projetos/', views.projetos_clientes, name='get_projetos'),
    path('criar_cargo/', views.criar_cargo, name='criar_cargo'),
    path('criar_funcionario/', views.criar_funcionario, name='criar_funcionario'),
    path('obter_funcionario/', views.obter_funcionario, name='obter_funcionario'),
    path('editar_funcionario/', views.editar_funcionario, name='editar_funcionario'),
    path('dados_graficos/', views.dados_graficos, name='dados_graficos'),
    path('aprovar_hora/', views.aprovar_hora, name='aprovar_hora'),
    path('reprovar_hora/', views.reprovar_hora, name='reprovar_hora'),
    path('invoices/', views.invoices, name='invoices'),

]

plataforma/models.py
from django.db import models
from django.utils import timezone
from login.models import Empresa, Pessoa

class EmpresaInfo(models.Model):
    EMI_COD = models.AutoField(primary_key=True)
    EMP_QUANTIDADE_FUNC = models.IntegerField()
    EMP_RAMO_ATUACAO = models.CharField(max_length=100, blank=True, null=True)
    EMP_COD = models.ForeignKey(Empresa, unique=True, on_delete=models.CASCADE)
    DATA_CRIACAO = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'EmpresaInfo' 

class Cargo(models.Model):
    CARGO_COD = models.AutoField(primary_key=True)
    CARGO_NOME = models.CharField(max_length=60, unique=True)
    CARGO_DT_ATUALIZACAO = models.DateTimeField(default=timezone.now)
    EMP_COD = models.ForeignKey(Empresa, on_delete=models.CASCADE, null=True)
    class Meta:
        db_table = 'Cargo' 

class Funcionario(models.Model):
    FUN_COD = models.AutoField(primary_key=True)
    PES_COD = models.ForeignKey(Pessoa, on_delete=models.CASCADE)
    EMP_COD = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    FUNC_DT_CADASTRO = models.DateTimeField(default=timezone.now)
    FUN_ROLES = models.ForeignKey(Cargo, on_delete=models.DO_NOTHING)
    FUN_MAXIMO_HORAS = models.IntegerField(blank=True, null=True)
    FUN_VALOR_HORA = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    FUN_APROVADO = models.CharField(max_length=1)
    FUN_TOKEN = models.CharField(max_length=200)
    FUN_TIPO = models.CharField(max_length=1)
    class Meta:
        db_table = 'Funcionario' 

class Cliente(models.Model):
    CLI_COD = models.AutoField(primary_key=True)
    CLI_NOME = models.CharField(max_length=50, blank=False, null=False)
    EMP_COD = models.ForeignKey(Empresa, on_delete=models.CASCADE)

    class Meta:
        db_table = 'Cliente' 

class Projeto(models.Model):
    PJT_COD = models.AutoField(primary_key=True)
    PJT_NOME = models.CharField(max_length=150)
    CLI_COD = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    PJT_VLR_HORA = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    PJT_OBSERVACAO = models.CharField(max_length=300)
    class Meta:
        db_table = 'Projeto' 

class Prioridade(models.Model):
    PRI_COD = models.AutoField(primary_key=True)
    PRI_NOME = models.CharField(max_length=50)

    class Meta:
        db_table = 'Prioridade' 

class Tarefas(models.Model):
    TRF_COD = models.AutoField(primary_key=True)
    PJT_COD = models.ForeignKey(Projeto, on_delete=models.CASCADE)
    TRF_TITULO = models.CharField(max_length=200, blank=False, null=False)
    FUN_COD = models.ForeignKey(Funcionario, on_delete=models.CASCADE)  # Mudou aqui
    TRF_PRIORIDADE = models.ForeignKey(Prioridade, on_delete=models.CASCADE)
    TRF_DATA_CONCLUSAO = models.DateTimeField(blank=True, null=True)
    TRF_STATUS = models.CharField(max_length=2, default='A')
    TRF_DATA_CRIACAO =  models.DateTimeField(auto_now=True)
    TRF_OBSERVACAO =  models.CharField(max_length=120, blank=True)
    class Meta:
        db_table = 'Tarefas' 


class Horas_Trabalhadas(models.Model):
    HRT_COD = models.AutoField(primary_key=True)
    HRT_DT_INICIO = models.DateTimeField(default=timezone.now)
    HRT_DT_FIM = models.DateTimeField(blank=True, null=True)
    PES_COD = models.ForeignKey(Pessoa, on_delete=models.CASCADE)
    TRF_COD = models.ForeignKey(Tarefas, on_delete=models.CASCADE)
    HRF_STATUS = models.CharField(max_length=2, default='A')
    class Meta:
        db_table = 'Horas_Trabalhadas' 


class Horas_Reprovadas(models.Model):
    HRR_COD = models.AutoField(primary_key=True)
    HRR_DT_ULTIMA = models.DateTimeField(default=timezone.now)
    HRR_JUSTIFICATIVA = models.CharField(max_length=200, blank=False, null=False)
    TRF_COD = models.ForeignKey(Tarefas, on_delete=models.CASCADE)
    class Meta:
        db_table = 'Horas_Reprovadas' 

class Horas_Aprovadas(models.Model):
    HRA_COD = models.AutoField(primary_key=True)
    HRA_DT_ULTIMA = models.DateTimeField(default=timezone.now)
    TRF_COD = models.ForeignKey(Tarefas, on_delete=models.CASCADE)
    class Meta:
        db_table = 'Horas_Aprovadas' 
        
class Pessoa_Pre_cadastro(models.Model):
    PPC_COD_PRE = models.AutoField(primary_key=True)
    PPC_TOKEN = models.CharField(max_length=200)
    PPC_ACCOUNT_ID = models.CharField(max_length=200)
    PPC_TOKEN = models.CharField(max_length=200)
    PPC_TOKEN = models.CharField(max_length=200)
    PPC_TOKEN = models.CharField(max_length=200)
    
    class Meta:
        db_table = 'Pessoa_Pre_cadastro' 
    
class EmpresaPessoaView(models.Model):
    pes_cod = models.IntegerField(primary_key=True) 
    pes_nome = models.CharField(max_length=150)
    emp_nome = models.CharField(max_length=150)
    emp_cod = models.IntegerField() 
    cargo_nome = models.CharField(max_length=150)
    Dono = models.IntegerField() 
    UltimoAcesso = models.CharField(max_length=150)

    class Meta():
        db_table = "SYS_LISTAR_EMPRESA_VI"
        managed = False
        
    
class HorasTarefasVI(models.Model):
    trf_cod = models.IntegerField(primary_key=True)
    fun_cod = models.IntegerField()
    emp_cod_id = models.IntegerField()
    trf_titulo = models.CharField(max_length=200)  
    pjt_nome = models.CharField(max_length=150)  
    pri_nome = models.CharField(max_length=50) 
    CLI_NOME = models.CharField(max_length=150)  
    total_tempo_trabalhado = models.CharField(max_length=40) 
    dt_inicio_iniciada = models.CharField(max_length=40) 
    status_tarefa = models.CharField(max_length=40) 
    class Meta:
        db_table = "SYS_TAREFAS_VI" 
        managed = False  
        
        
class SysDetalhesTarefasVi(models.Model):
    trf_cod = models.IntegerField(primary_key=True)
    nome_tarefa = models.CharField(max_length=200)
    nome_cliente = models.CharField(max_length=50)
    prioridade = models.CharField(max_length=50)
    total_horas_trabalhadas = models.CharField(max_length=40) 
    trf_data_conclusao = models.CharField(max_length=10) 
    status = models.CharField(max_length=9)
    trf_data_criacao = models.CharField(max_length=10)  
    trf_status = models.CharField(max_length=10)
    fun_cod = models.IntegerField()  
    pes_cod = models.IntegerField()  
    HRR_JUSTIFICATIVA = models.CharField(max_length=255, null=True, blank=True) 

    class Meta:
        managed = False 
        db_table = 'SYS_DETALHES_TAREFAS_VI'  
        
        
        
class SysGraficosHorasVi(models.Model):
    HRT_COD = models.IntegerField()
    trf_titulo = models.CharField(max_length=255) 
    data_inicio = models.CharField(max_length=10)
    data_fim = models.CharField(max_length=10) 
    total_trabalhado = models.TimeField() 
    PES_COD_id = models.IntegerField()
    TRF_COD_id = models.IntegerField(primary_key=True)
    HRF_STATUS = models.CharField(max_length=2) 
    class Meta:
        managed = False  
        db_table = 'SYS_GRAFICOS_HORAS_VI'
        
        
    
class SysEquipeVi(models.Model):
    pes_nome = models.CharField(max_length=255)
    pes_email = models.EmailField()
    cargo_nome = models.CharField(max_length=255)
    trabalho = models.BooleanField()
    pes_foto_url = models.URLField(max_length=500, null=True, blank=True)
    pes_cod = models.BigIntegerField()
    fun_cod = models.BigIntegerField(primary_key=True)
    emp_cod_id = models.BigIntegerField()
    Inicial = models.CharField(max_length=1)

    class Meta:
        managed = False 
        db_table = 'SYS_EQUIPE_VI'
        
        

class FaturasPrevistaVI(models.Model):
    data_trabalho = models.DateField(primary_key=True)
    total_horas = models.DecimalField(max_digits=10, decimal_places=2)
    ganho_total = models.DecimalField(max_digits=10, decimal_places=2)
    pes_cod = models.BigIntegerField()
    fun_cod = models.BigIntegerField()
    TRF_COD_id = models.BigIntegerField()
    class Meta:
        managed = False  
        db_table = 'SYS_FATURAS_PREVISTA_VI'
        
        
class Invoice(models.Model):
    INV_ID = models.AutoField(primary_key=True)
    CLI_COD = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    EMP_COD = models.ForeignKey(Empresa,  on_delete=models.CASCADE)
    FUN_COD = models.ForeignKey(Funcionario, on_delete=models.CASCADE)
    DATA_EMISSAO = models.DateTimeField(auto_now_add=True)
    TOTAL_HORAS = models.DecimalField(max_digits=10, decimal_places=2)
    TOTAL_VALOR = models.DecimalField(max_digits=10, decimal_places=2)
    STATUS = models.CharField(max_length=10)

    class Meta:
        db_table = 'invoice'
       

plataforma/templates/cadastrar_tarefa.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}

<title>SysTimer - Home</title>
{% endblock %}

{% block conteudo %}
<form method="POST" action="{% url 'cadastrar_tarefa'%}">
    <div class="h-[80px] flex items-center justify-between w-full p-5">
        <div class="flex items-center  w-full justify-between p-1rounded-xl">
            <div>
                <div class="text-[10px] flex items-center  font-semibold text-neutral-400">
                    <a class="flex items-center mb-2" href="{% url 'renderizar_plataforma' %}">
                        <i class="fa-solid fa-chevron-left font-bold text-xs"></i>
                        <span class="ml-2 text-xs"> Retornar Acompanhamento Tarefas</span>
                    </a>
                </div>
                <div>
                    <span class="text-2xl font-semibold">
                        Cadastrar Nova Tarefa
                    </span>
                </div>
            </div>

            <div class="flex p-3 items-center">
                <button type="submit"
                    class="flex justify-centeri bg-blue-500 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                        class="icon icon-tabler icons-tabler-outline icon-tabler-plus">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                        <path d="M12 5l0 14" />
                        <path d="M5 12l14 0" />
                    </svg>
                    Salvar Tarefa
                </button>
            </div>
        </div>
    </div>
    <hr>
    <div>
</div>


    {% csrf_token %}
    <div class="p-4 space-y-4">
        <div>
            <label for="id_titulo" class="block text-sm font-medium text-gray-700">Título</label>
            <input type="text" name="titulo" id="id_titulo"
                class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                placeholder="Digite o título da Tarefa" required>
        </div>

        <div class="flex w-full ">
            <div class="flex w-full items-center mr-10">
                <div  class="w-full mr-2">
                    <label for="id_cliente" class="block text-sm font-medium text-gray-700">Cliente</label>
                    <select name="cliente" id="id_cliente"
                        class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                        onchange="filtrarProjetos()" required>
                        <option value="">Selecione um Cliente</option>
                        {% for cliente in clientes %}
                        <option value="{{ cliente.CLI_COD }}">{{ cliente.CLI_NOME }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="w-[30%] mt-5 ">
                    <span>ou</span>
                    <button type="button" data-modal-target="crud-modal" data-modal-toggle="crud-modal"
                        class="ml-4 bg-blue-500 text-white px-3 py-2 rounded-lg hover:bg-blue-600 focus:ring-4 focus:ring-blue-300 dark:bg-blue-700 dark:hover:bg-blue-800 dark:focus:ring-blue-900">
                        + Cliente
                    </button>
                </div>
            </div>

            <div class="w-full">
                <label for="id_projeto" class="block text-sm font-medium text-gray-700">Projeto</label>
                <select name="projeto" id="id_projeto"
                    class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                    required>
                    <option value="">Selecione um Projeto</option>
                </select disabled>
            </div>
        </div>

        <div class="flex">



            <div class="w-[50%]  mr-10">
                <label for="id_funcionario" class="block text-sm font-medium text-gray-700">Responsável</label>

                {% if cargo == 'Administrador'%}
                <select name="funcionario" id="id_funcionario"
                    class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                    required>
                    {% for funcionario in funcionarios %}
                    <option value="{{ funcionario.FUN_COD }}">
                        {{ funcionario.PES_COD.PES_NOME }} {{ funcionario.PES_COD.PES_SOBRENOME }}</option>
                    {% endfor %}
                </select>
                {% else %}
                <select  name="funcionario" id="id_funcionario"
                    class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                    required>
                    {% for funcionario in funcionarios %}
                    <option  value="{{ funcionario.FUN_COD }}">
                        {{ funcionario.PES_COD.PES_NOME }}  {{ funcionario.PES_COD.PES_SOBRENOME }}
                    </option>
                    {% endfor %}
                </select>
                {% endif %}
            </div>

            <div class="w-[50%]">
                <label for="id_prioridade" class="block text-sm font-medium text-gray-700">Prioridade</label>
                <select name="prioridade" id="id_prioridade"
                    class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                    required>
                    <option  value="">Selecione a Prioridade</option>
                    {% for prioridade in prioridades %}
                    <option name="funcionario" value="{{ prioridade.PRI_COD }}">{{ prioridade.PRI_NOME }}</option>
                    {% endfor %}
                </select>
            </div>


        </div>

        <div>
            <label for="message" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Observação</label>
            <textarea id="message" name="obs" rows="4" maxlength="150"
                class="block p-2.5 w-full h-[200px] resize-none length text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                placeholder="Digite a observação que deseja da sua tarefa..."></textarea>
        </div>

    </div>
</form>


<div id="crud-modal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed inset-0 z-50 flex justify-center items-center w-full h-full bg-black bg-opacity-50">    <div class="relative p-4 w-full max-w-md max-h-full">
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                <h3 class="text-lg font-semibold text-gray-900 dark:text-white">
                    Novo Cliente
                </h3>
                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="crud-modal">
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <form class="p-4 md:p-5" method="POST" action="{% url 'criar_cliente' %}">
                {% csrf_token %}
                <div class="grid gap-4 mb-4 grid-cols-2">
                    <div class="col-span-2">
                        <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Nome Cliente</label>
                        <input type="text" name="nome_cliente" id="nome_cliente" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Nome do Cliente" required="">
                    </div>

                </div>
                <button type="submit" class="text-white inline-flex items-center bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                    <svg class="me-1 -ms-1 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clip-rule="evenodd"></path></svg>
                    Adicionar Cliente
                </button>
            </form>
        </div>
    </div>
</div> 


<script src="{% static '/js/editor.js' %}" type="module" defer></script>

<script>

    function filtrarProjetos() {
        const clienteSelecionado = document.getElementById('id_cliente').value;
        const projetoSelect = document.getElementById('id_projeto');

        projetoSelect.innerHTML = '<option value="">Selecione um Projeto</option>';

        if (clienteSelecionado) {
            fetch(`/plataforma/get-projetos/?cliente_cod=${clienteSelecionado}`)
                .then(response => response.json())
                .then(data => {
                    if (data.projetos) {
                        data.projetos.forEach(projeto => {
                            const option = document.createElement('option');
                            option.value = projeto.PJT_COD;
                            option.textContent = projeto.PJT_NOME;
                            projetoSelect.appendChild(option);
                        });
                    } else {
                        alert('Nenhum projeto encontrado para este cliente.');
                    }
                })
                .catch(error => {
                    console.error('Erro ao buscar projetos:', error);
                });
        }
    }
</script>

{% endblock %}

plataforma/templates/editar_usuario.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title>SysTimer - Editar Usuário</title>
{% endblock %}

{% block conteudo %}
<div class="min-h-screen flex items-center justify-center bg-gray-100 py-12 px-6">
    <div class="bg-white p-8 rounded-lg shadow-lg w-full max-w-md">
        <h2 class="text-2xl font-bold mb-6 text-center text-gray-800">Editar Usuário</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            
            <!-- Nome -->
            <div class="mb-4">
                <label for="nome" class="block text-sm font-medium text-gray-700">Nome</label>
                <input type="text" id="nome" name="nome" class="mt-1 block w-full p-3 border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500" placeholder="Digite seu nome" value="{{ pessoa.PES_NOME }}">
            </div>

            <!-- Sobrenome -->
            <div class="mb-4">
                <label for="sobrenome" class="block text-sm font-medium text-gray-700">Sobrenome</label>
                <input type="text" id="sobrenome" name="sobrenome" class="mt-1 block w-full p-3 border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500" placeholder="Digite seu sobrenome" value="{{ pessoa.PES_SOBRENOME }}">
            </div>

            <!-- Email -->
            <div class="mb-4">
                <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
                <input type="email" id="email" name="email" class="mt-1 block w-full p-3 border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500" placeholder="Digite seu email" value="{{ pessoa.PES_EMAIL}}">
            </div>

            <!-- Foto -->
            <div class="mb-4">
                <label for="foto" class="block text-sm font-medium text-gray-700">Foto</label>
                <input type="file" id="foto" name="foto" class="mt-1 block w-full text-gray-700 file:mr-4 file:py-2 file:px-4 file:rounded-lg file:border file:border-gray-300 file:text-sm file:font-medium file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100">
                {% if pessoa.foto %}
                    <div class="mt-2">
                        <img src="{{ pessoa.foto.url }}" alt="Foto do usuário" class="w-24 h-24 object-cover rounded-full">
                    </div>
                {% endif %}
            </div>

            <!-- Senha -->
            <div class="mb-4">
                <label for="senha" class="block text-sm font-medium text-gray-700">Senha</label>
                <input type="password" id="senha" name="senha" class="mt-1 block w-full p-3 border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500" placeholder="Digite sua nova senha">
            </div>

            

            <!-- Cargo --> 
            <div class="mb-4">
                <label for="cargo" class="block text-sm font-medium text-gray-700">Cargo</label>
                <select id="cargo" name="cargo" class="mt-1 block w-full p-3 border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500">
                    <option value="Administrador" {% if pessoa.cargo == 'Administrador' %}selected{% endif %}>Administrador</option>
                    <option value="Usuário" {% if pessoa.cargo == 'Usuário' %}selected{% endif %}>Usuário</option>
                    <option value="Gerente" {% if pessoa.cargo == 'Gerente' %}selected{% endif %}>Gerente</option>
                </select>
            </div>

            <!-- Botão de enviar -->
            <div class="mt-6">
                <button type="submit" class="w-full bg-blue-600 text-white py-3 rounded-lg shadow-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2">Salvar Alterações</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

plataforma/templates/inicio.html
{% extends 'base.html' %}

{% block 'conteudo' %}

<h1 class="bg-red-500">Renê</h1>


{% endblock %}